build:
  version: "1.0"

accounts:
  message: "Welcome to EazyBank cards related prod APIs"
  contactDetails:
    name: "Saffron Aishwarva - Product Owner"
    email: "saffron@gmail.com"
  onCallSupport:
    - (31)3322-3434
    - (31)3222-4343