build:
  version: "3.0"

accounts:
  message: "Welcome to EazyBank loans related local APIs"
  contactDetails:
    name: "roberta Doe - Developer"
    email: "roberta@gmail.com"
  onCallSupport:
    - (31)5555-3333
    - (31)3335-3635