spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

loans:
  message: "Welcome to EazyBank loans related QA APIs"
  contactDetails:
    name: "Stefany - QA Lead"
    email: "stefany@gmail.com"
  onCallSupport:
    - (31)4565-3434
    - (31)6768-4343