
spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

accounts:
  message: "Welcome to EazyBank accounts related QA APIs"
  contactDetails:
    name: "Smith Ray - QA Lead"
    email: "smitha@gmail.com"
  onCallSupport:
    - (31)3333-3434
    - (31)3333-4343